# max_width             = 160
# ideal_width           = 128
# fn_call_width         = 96
# fn_args_paren_newline = false
# fn_args_density       = "Compressed"
# struct_trailing_comma = "Always"
# wrap_comments         = true
error_on_line_overflow = false
format_strings = true
# force_format_strings = true
normalize_comments = true
# reorder_imported_names = true
# reorder_imports = true
merge_imports = true
reorder_impl_items = true
reorder_modules = true
enum_discrim_align_threshold = 20
# skip_children = true
use_try_shorthand = true
wrap_comments = true
match_block_trailing_comma = false
trailing_comma = "Never"
# closure_block_indent_threshold=-1
edition = "2018"
tab_spaces = 2
